export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const POST_PRODUCT = "POST_PRODUCT";
/* User */
export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const DELETE_USER = "DELETE_USER";
export const POST_USER = "POST_USER";
export const UPDATE_USER = "UPDATE_USER";
export const REGISTER_USER = "REGISTER_USER";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNIN_ERRORS = "SIGNIN_ERRORS";
export const REGISTER_ERRORS = "REGISTER_ERRORS";
export const CLEAN_MSG_REGISTER_USER = "CLEAN_MSG_REGISTER_USER";
export const SET_USER = "SET_USER";

/* filter */
export const CREATE_PAGINATION_ARRAY = "CREATE_PAGINATION_ARRAY";
export const FILTEREDBREED = "FILTEREDBREED";
export const FILTEREDSIZE = "FILTEREDSIZE";
export const SORT = "SORT";
export const SEARCH = "SEARCH";
export const FILTERED = "FILTERED";
/* ShoppingCart */

export const POST_CARTDTAIL = "POST_CARTDTAIL";
export const GET_CARTDTAIL = "GET_CARTDTAIL";
export const UPDATE_CARTDTAIL = "UPDATE_CARTDTAIL";
export const DELETE_CARTDTAIL = "DELETE_CARTDTAIL";
export const DIFFERENT_OUTCOME = "DIFFERENT_OUTCOME";
export const EMPTY_DIFFOUTCOME_OBJ = "EMPTY_DIFFOUTCOME_OBJ";
export const EMPTY_SHOPPINGCARTDTAIL = "EMPTY_SHOPPINGCARTDTAIL";
export const EMPTY_SHOPPINGCARTDTAILMSG = "EMPTY_SHOPPINGCARTDTAILMSG";

/* Dashboard */
export const SEARCH_PRO_DASHBOARD = "SEARCH_PRO_DASHBOARD";
export const BY_ORDER = "BY_ORDER";
export const BY_ORDER_PRICE = "BY_ORDER_PRICE";
export const BY_ORDER_STOCK = "BY_ORDER_STOCK";

/* Favorites */
export const GET_FAVORITES = "GET_FAVORITES";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE";

export const SEARCH_USERS_DASHBOARD = "SEARCH_USERS_DASHBOARD";

export const POST_FAVORITES = "POST_FAVORITES";
